name: Automated tests

on:
  push:
  pull_request:

jobs:
  test_runner:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run web client
        shell: bash
        run: | 
          python -m http.server 8000 &
          for i in $(seq 1 30); do
            curl --fail http://localhost:8000 && echo "Server is up!" && exit 0
            echo "Waiting for server... Attempt $i"
            sleep 2
          done
          python -m unittest discover -s tests -v