name: Automated tests

on:
  push:
  pull_request:

jobs:
  test_runner:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run web client
        shell: cmd
        run: start /b python -m http.server 8000
      - name: Wait for web client
        shell: powershell
        run: |
          for ($i=1; $i -le 10; $i++) {
            try {
              $response = Invoke-WebRequest -Uri http://localhost:8000 -UseBasicParsing -TimeoutSec 1
              if ($response.StatusCode -eq 200) { exit 0 }
            } catch {
              # игнорируем ошибки
            }
            Start-Sleep -Seconds 1
          }
          exit 1
      - name: Run tests
        run: python -m unittest discover -s tests