name: Automated tests

on:
  push:
  pull_request:

jobs:
  test_runner:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run web client
        shell: bash
        run: | 
          python -m http.server 8000 &
          sleep 7
          python -m unittest discover -s tests -v