name: Automated tests

on:
  push:
  pull_request:

jobs:
  test_runner:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run web client
        shell: cmd
        run: start /b python -m http.server 8000
      - name: Wait for web client
        shell: cmd
        run: |
          for /L %%i in (1,1,10) do (
            curl http://localhost:8000 >nul 2>&1 && exit /b 0
            timeout /t 1 >nul
          )
      - name: Run tests
        run: python -m unittest discover -s tests